language: generic

os: osx
osx_image: xcode7.3

env:
  global:
    - MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  matrix:
    - CONFIG=2.7
    - CONFIG=3.6.2=0
    - CONFIG=3.6.1=2
    - CONFIG=3.6.1=0
    - CONFIG=3.6.0
    - CONFIG=3.5.6
    - CONFIG=3.5.5=*_3
    - CONFIG=3.5.5=*_1
    - CONFIG=3.5.5=*_0


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


script:
  - bash ci_support/build_recipe.sh ${CONFIG}
