package:
    name: eman2
    version: 2.22

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_host = [
            "msinttypes",  # [win]
            "python 2.7.14",
            "boost 1.63.*",
            "fftw-mpi",
            "numpy 1.13.*",
            "ftgl",
            "freetype 2.8.*",  # [osx]
            "freetype 2.7.*",  # [not osx]
            "gsl",
            "hdf5 1.8.18",
            "jpeg",
            "libtiff 4.0.9",             # [not win]
            "libtiff 4.0.9 hafacce9_0",  # [win]
            "libpng 1.6.34",
            "zlib",
    ] %}
    
    build:
        - cmake 3.9
        - {{ compiler('cxx') }}
        - {{ cdt('libxcb') }}               # [linux]
        - {{ cdt('libxi-devel') }}          # [linux]
        - {{ cdt('libx11-devel') }}         # [linux]
        - {{ cdt('libxau-devel') }}         # [linux]
        - {{ cdt('libxext-devel') }}        # [linux]
        - {{ cdt('libxfixes-devel') }}      # [linux]
        - {{ cdt('mesa-libgl-devel') }}     # [linux]
        - {{ cdt('xorg-x11-proto-devel') }} # [linux]

    host:
        {% for req in reqs_host %}
        - {{ req }}
        {% endfor %}
        - libglu      # [linux]
    
test:
  requires:
    - openmpi              # [not win]
    - eman-deps=14.0
  
  source_files:
    - examples/mpi_test.py
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
