package:
    name: eman2
    version: 2.31

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    build:
        - cmake     3.14.*
        - {{ compiler('cxx') }}           # [not win]
        - {{ cdt('mesa-libgl-devel') }}   # [linux]

    host:
        - python    3.6.*
        - boost     1.64.*
        - fftw-mpi
        - numpy     1.13.*
        - ftgl
        - freetype
        - gsl
        - hdf5      1.8.18
        - jpeg
        - libtiff   4.0.9
        - libpng    1.6.36
        - zlib
        - libglu                          # [linux]
    
test:
  requires:
    - openmpi                             # [not win]
    - eman-deps     18.0.*
    - boost         1.64.*
  
  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh             # [not win]
    - call tests\run_tests.bat            # [win]
