package:
    name: eman2
    version: 2.21

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "msinttypes",  # [win]
            "python 2.7.14",
            "boost 1.63.*",
            "fftw-mpi",
            "numpy 1.13.*",
            "ftgl",
            "freetype 2.8.*",  # [osx]
            "freetype 2.7.*",  # [not osx]
            "gsl",
            "hdf5 1.8.18",
            "jpeg",
            "libtiff 4.0.9",            # [not win]
            "libtiff 4.0.9 hafacce9_0",  # [win]
            "libpng 1.6.34",
            "zlib",
            "matplotlib 2.1.*",  # [osx]
            "matplotlib 1.5.*",  # [not osx]
            "scipy 1.*",
            "ipython",
            "pyqt 4.11.*",
            "qt >=4.8.6",
            "pyopengl 3.1.0",
            "theano 1.0.*",
            "scikit-learn 0.19.*",
            "bsddb",          # [not win]
            "openmpi 2.0.2",  # [not win]
            "pydusa",         # [not win]
            "nose",
            "pyautogui",
            "pytest",
            "pytest-qt",
    ] %}
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

build:
  script_env:
   - EMAN_TEST_SKIP  # [osx]

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py
    - tests/run_tests.sh
    - tests/run_tests.bat

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
