package:
    name: eman2
    version: 2.3

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_host = [
            "msinttypes",  # [win]
            "boost 1.64.*",
            "python 3.6.*",    # [not osx]
            "python 3.6.1 2",  # [osx]
            "fftw-mpi",
            "numpy 1.13.*",
            "ftgl",
            "freetype",
            "gsl",
            "hdf5 1.8.18",
            "jpeg",
            "libtiff",
            "libpng 1.6.36",
            "zlib",
            "future",
            "configparser",
    ] %}
    
    {% set reqs_run = [
            "matplotlib >3.0.0",
            "scipy 1.*",
            "ipython",
            "pyqt 5.*",
            "pyopengl 3.1.0",
            "scikit-learn 0.19.*",
            "bsddb3",          # [not win and py3k]
            "bsddb",           # [not win and py2k]
#            "openmpi 2.0.2",  # [not win]
#            "pydusa",         # [not win]
            "nose",
            "future",
            "configparser",
    ] %}

    build:
        - cmake 3.9
        - {{ compiler('cxx') }}       # [not win]

    host:
        {% for req in reqs_host %}
        - {{ req }}
        {% endfor %}
        
    run:
        {% for package in resolved_packages('host') %}
        - {{ package }}
        {% endfor %}
        {% for req in reqs_run %}
        - {{ req }}
        {% endfor %}

    
test:
  requires:
    - openmpi              # [not win]
    - boost 1.64.*
    - eman-deps=15.4
  
  source_files:
    - examples/mpi_test.py
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
