find_package(Python REQUIRED COMPONENTS Interpreter Development)

set(CMAKE_FIND_FRAMEWORK_BACK ${CMAKE_FIND_FRAMEWORK})
set(CMAKE_FIND_FRAMEWORK NEVER)
set(Python_FIND_REGISTRY NEVER)

set(CMAKE_FIND_FRAMEWORK ${CMAKE_FIND_FRAMEWORK_BACK})
unset(CMAKE_FIND_FRAMEWORK_BACK)

message("PYTHON_EXECUTABLE:   ${Python_EXECUTABLE}")
message("PYTHON_LIBRARIES:    ${Python_LIBRARIES}")
message("PYTHON_INCLUDE_DIRS: ${Python_INCLUDE_DIRS}")
message("Python site-packages: ${Python_SITELIB}")
message("Python_INTERPRETER_ID: ${Python_INTERPRETER_ID}")
